In [1]:
import numpy as np
import seaborn as sns
import pandas as pd

In [2]:
resturant = sns.load_dataset('tips')
resturant

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
resturant[	'total_bill'	]

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [7]:
total_bill = list(resturant[	'total_bill'	])

In [12]:
total_bill2 = np.array(total_bill)
print(total_bill2)

[16.99 10.34 21.01 23.68 24.59 25.29  8.77 26.88 15.04 14.78 10.27 35.26
 15.42 18.43 14.83 21.58 10.33 16.29 16.97 20.65 17.92 20.29 15.77 39.42
 19.82 17.81 13.37 12.69 21.7  19.65  9.55 18.35 15.06 20.69 17.78 24.06
 16.31 16.93 18.69 31.27 16.04 17.46 13.94  9.68 30.4  18.29 22.23 32.4
 28.55 18.04 12.54 10.29 34.81  9.94 25.56 19.49 38.01 26.41 11.24 48.27
 20.29 13.81 11.02 18.29 17.59 20.08 16.45  3.07 20.23 15.01 12.02 17.07
 26.86 25.28 14.73 10.51 17.92 27.2  22.76 17.29 19.44 16.66 10.07 32.68
 15.98 34.83 13.03 18.28 24.71 21.16 28.97 22.49  5.75 16.32 22.75 40.17
 27.28 12.03 21.01 12.46 11.35 15.38 44.3  22.42 20.92 15.36 20.49 25.21
 18.24 14.31 14.    7.25 38.07 23.95 25.71 17.31 29.93 10.65 12.43 24.08
 11.69 13.42 14.26 15.95 12.48 29.8   8.52 14.52 11.38 22.82 19.08 20.27
 11.17 12.26 18.26  8.51 10.33 14.15 16.   13.16 17.47 34.3  41.19 27.05
 16.43  8.35 18.64 11.87  9.78  7.51 14.07 13.13 17.26 24.55 19.77 29.85
 48.17 25.   13.39 16.49 21.5  12.66 16.21 13.81 17.

In [11]:
a= np.array([1,2,3,4])
b= np.array([1,5,6,7,9,10])
print(a)
print(b)

[1 2 3 4]
[ 1  5  6  7  9 10]


In [15]:
total_bill2.mean()

19.78594262295082

In [16]:
total_bill2.sum()

4827.77

In [17]:
total_bill2.std()

8.884150577771132

In [18]:
total_bill = total_bill2
size = np.array(resturant['size'])
print(size)

[2 3 3 2 4 4 2 4 2 2 2 4 2 4 2 2 3 3 3 3 2 2 2 4 2 4 2 2 2 2 2 4 2 4 2 3 3
 3 3 3 3 2 2 2 4 2 2 4 3 2 2 2 4 2 4 2 4 2 2 4 2 2 2 4 3 3 2 1 2 2 2 3 2 2
 2 2 2 4 2 2 2 2 1 2 2 4 2 2 2 2 2 2 2 2 2 4 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2
 1 3 2 3 2 4 2 2 4 2 2 2 2 2 6 2 2 2 3 2 2 2 2 2 2 2 2 2 2 2 6 5 6 2 2 3 2
 2 2 2 2 3 4 4 5 6 4 2 4 4 2 3 2 2 3 2 4 2 2 3 2 2 2 2 2 2 2 2 2 4 2 3 4 2
 5 3 5 3 3 2 2 2 2 2 2 2 4 2 2 3 2 2 2 4 3 3 4 2 2 3 4 4 2 3 2 5 2 2 4 2 2
 1 3 2 2 2 4 2 2 4 3 2 2 2 2 2 2 3 3 2 2 2 2]


In [19]:
size.mean()

2.569672131147541

In [20]:
total_bill>20

array([False, False,  True,  True,  True,  True, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False,  True, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False,  True,
       False, False, False,  True, False, False, False, False,  True,
       False,  True,  True,  True, False, False, False,  True, False,
        True, False,  True,  True, False,  True,  True, False, False,
       False, False,  True, False, False,  True, False, False, False,
        True,  True, False, False, False,  True,  True, False, False,
       False, False,  True, False,  True, False, False,  True,  True,
        True,  True, False, False,  True,  True,  True, False,  True,
       False, False, False,  True,  True,  True, False,  True,  True,
       False, False, False, False,  True,  True,  True, False,  True,
       False, False,  True, False, False, False, False, False,  True,
       False, False,

In [21]:
(total_bill>20).sum()

97

In [22]:
total_bill.max()

50.81

In [28]:
two_d = np.array([[1,2,3],[4,5,6]])

In [29]:
two_d.shape

(2, 3)

In [30]:
print(two_d)

[[1 2 3]
 [4 5 6]]


In [31]:
two_d[1]

array([4, 5, 6])

In [32]:
two_d[0]

array([1, 2, 3])